export const UTILISATEUR_REPOSITORY = Symbol("UTILISATEUR_REPOSITORY");
export const AUTH_SERVICE = Symbol("AUTH_SERVICE");
export const ACTIVITE_REPOSITORY = Symbol("ACTIVITE_REPOSITORY");
export const DISPONIBILITE_JOURNEE_REPOSITORY = Symbol(
  "DISPONIBILITE_JOURNEE_REPOSITORY",
);
export const DISPONIBILITE_ACTIVITE_REPOSITORY = Symbol(
  "DISPONIBILITE_ACTIVITE_REPOSITORY",
);
export const SOURCE_MATCHS_DISTRICT = Symbol("SOURCE_MATCHS_DISTRICT");
